-- ALPA SAAS UNIFICADO - Supabase Schema
-- Run this in the Supabase SQL Editor

-- 0. EXTENSIONS & HELPERS
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Helper function for RLS (Moved to public to avoid permission issues)
CREATE OR REPLACE FUNCTION public.get_tenant_id() RETURNS uuid AS $$
  SELECT (nullif(auth.jwt() ->> 'organization_id', ''))::uuid;
$$ LANGUAGE sql STABLE;

-- 0.1 ORGANIZATIONS TABLE
CREATE TABLE IF NOT EXISTS public.organizations (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    name TEXT NOT NULL,
    rut TEXT UNIQUE,
    plan_id UUID,                -- For future subscription module
    settings JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 0.2 ORGANIZATION MEMBERS TABLE
CREATE TABLE IF NOT EXISTS public.organization_members (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    organization_id UUID NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    role TEXT NOT NULL DEFAULT 'member',  -- 'admin', 'member', 'viewer'
    invited_at TIMESTAMPTZ DEFAULT NOW(),
    joined_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(organization_id, user_id)
);

CREATE INDEX idx_org_members_org ON public.organization_members(organization_id);
CREATE INDEX idx_org_members_user ON public.organization_members(user_id);

-- 1. CLIENTS TABLE
CREATE TABLE IF NOT EXISTS public.clients (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id UUID NOT NULL REFERENCES public.organizations(id),
    name TEXT NOT NULL,
    rut TEXT,
    contact TEXT,
    phone TEXT,
    email TEXT,
    origin TEXT DEFAULT 'Direct',
    created_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX idx_clients_org ON public.clients(organization_id);

-- 2. PROVIDERS TABLE
CREATE TABLE IF NOT EXISTS public.providers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id UUID NOT NULL REFERENCES public.organizations(id),
    name TEXT NOT NULL,
    rut TEXT,
    contact TEXT,
    phone TEXT,
    email TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX idx_providers_org ON public.providers(organization_id);

-- 3. INVENTORY TABLE
CREATE TABLE IF NOT EXISTS public.inventory (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id UUID NOT NULL REFERENCES public.organizations(id),
    name TEXT NOT NULL,
    sku TEXT UNIQUE,
    stock INTEGER DEFAULT 0,
    unit TEXT DEFAULT 'unidad',
    created_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX idx_inventory_org ON public.inventory(organization_id);

-- 4. PROJECTS TABLE
CREATE TABLE IF NOT EXISTS public.projects (
    id TEXT PRIMARY KEY,
    organization_id UUID NOT NULL REFERENCES public.organizations(id),
    name TEXT NOT NULL,
    code TEXT,
    client TEXT,
    client_rut TEXT,
    budget NUMERIC(15, 2) DEFAULT 0,
    status TEXT DEFAULT 'Activo',
    start_date DATE,
    end_date DATE,
    responsible TEXT,
    payment_statuses JSONB DEFAULT '[]'::jsonb,
    created_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX idx_projects_org ON public.projects(organization_id);

-- 5. TRANSACTIONS TABLE
CREATE TABLE IF NOT EXISTS public.transactions (
    id TEXT PRIMARY KEY,
    organization_id UUID NOT NULL REFERENCES public.organizations(id),
    date DATE NOT NULL,
    type TEXT NOT NULL,
    category TEXT,
    amount NUMERIC(15, 2) NOT NULL,
    description TEXT,
    cost_center TEXT,
    status TEXT DEFAULT 'Vigente',
    created_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX idx_transactions_org ON public.transactions(organization_id);

-- 6. LEADS TABLE
CREATE TABLE IF NOT EXISTS public.leads (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id UUID NOT NULL REFERENCES public.organizations(id),
    name TEXT NOT NULL,
    email TEXT NOT NULL,
    phone TEXT,
    message TEXT,
    status TEXT DEFAULT 'Nuevo',
    source TEXT DEFAULT 'Web',
    created_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX idx_leads_org ON public.leads(organization_id);

-- Enable Row Level Security (RLS)
ALTER TABLE public.organizations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.organization_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.clients ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.providers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.inventory ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.leads ENABLE ROW LEVEL SECURITY;

-- POLICIES

-- Organizations: Users can see their own organization
CREATE POLICY "Users can see their own organization" 
ON public.organizations FOR SELECT 
USING (id = public.get_tenant_id());

-- Organization Members: Users can see their own membership
CREATE POLICY "Users can see their own memberships" 
ON public.organization_members FOR SELECT 
USING (user_id = auth.uid());

-- Data Tables Policies
CREATE POLICY "Multi-tenant access" ON public.clients
FOR ALL USING (organization_id = public.get_tenant_id()) WITH CHECK (organization_id = public.get_tenant_id());

CREATE POLICY "Multi-tenant access" ON public.providers
FOR ALL USING (organization_id = public.get_tenant_id()) WITH CHECK (organization_id = public.get_tenant_id());

CREATE POLICY "Multi-tenant access" ON public.inventory
FOR ALL USING (organization_id = public.get_tenant_id()) WITH CHECK (organization_id = public.get_tenant_id());

CREATE POLICY "Multi-tenant access" ON public.projects
FOR ALL USING (organization_id = public.get_tenant_id()) WITH CHECK (organization_id = public.get_tenant_id());

CREATE POLICY "Multi-tenant access" ON public.transactions
FOR ALL USING (organization_id = public.get_tenant_id()) WITH CHECK (organization_id = public.get_tenant_id());

CREATE POLICY "Multi-tenant access" ON public.leads
FOR ALL USING (organization_id = public.get_tenant_id()) WITH CHECK (organization_id = public.get_tenant_id());
